[build-system]
    requires = ["setuptools", "wheel", "bob.extension"]
    build-backend = "setuptools.build_meta"

[tool.isort]
    profile = "black"
    line_length = 80
    dont_order_by_type = true

[tool.black]
    line-length = 80
