{% set name = 'bob.ip.binseg' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - python setup.py install --single-version-externally-managed --record record.txt
    # installs the documentation source, readme to share/doc so it is available
    # during test time
    - install -d "${PREFIX}/share/doc/{{ name }}"
    - cp -R README.rst requirements.txt doc "${PREFIX}/share/doc/{{ name }}/"

requirements:
  # place your build dependencies before the 'host' section
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - torchvision  {{ torchvision }}
    - pytorch {{ pytorch }}
    - numpy {{ numpy }}
    - bob.extension
    # place your other host dependencies here
  run:
    - python
    - setuptools
    - {{ pin_compatible('pytorch') }}
    - {{ pin_compatible('torchvision') }}
    - {{ pin_compatible('numpy') }}
    - pandas
    - matplotlib
    - bob.db.drive
    - bob.db.stare
    - bob.db.chasedb1
    - bob.db.hrf
    - bob.db.drionsdb
    - bob.db.rimoner3
    - bob.db.drishtigs1
    - bob.db.refuge
    - bob.db.iostar
    # place other runtime dependencies here (same as requirements.txt)

test:
  imports:
    - {{ name }}
  commands:
    # test commands ("script" entry-points) from your package here
    - bob binseg --help
    - bob binseg train --help
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - bob-devel {{ bob_devel }}.*
    - nose
    - coverage
    - sphinx
    - sphinx_rtd_theme
    # extend this list with further test-time-only dependencies

about:
  summary: Binary Segmentation Benchmark Package for Bob
  home: https://www.idiap.ch/software/bob/
  license: GNU General Public License v3 (GPLv3)
  license_family: GPL
  license_file: ../COPYING